apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calorielens
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CalorieLens/CalorieLens-manifests
    targetRevision: main
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: calorielens
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
